### ISSUE TITLE
How to find another type of icon for social link?

### ISSUE THREAD

**Issue by ryanadhi** [EmaSuriano/gatsby-starter-mate#357]
I tried to put 'youtube' on the icon (contentful) but it shows the old logo, even though if I am trying to search 'youtube' on font awesome, it shows recent logo

**Comment by EmaSuriano** [comment]
Hey @ryanadhi yeah it was a problem in the previous version mainly because the icons were hard coded inside the `static` folder, to reduce the amount of icons requested. I moved into using a library to manage font-awesome icons, that also has a good result into Lighthouse score. You can see the changes here --> #380 

Please let me know if it worked for you!
