### ISSUE TITLE
Using Input Component

### ISSUE THREAD

**Issue by azrijamil** [EmaSuriano/gatsby-starter-mate#39]
how to use Input(form) component from react-bootstrap or any others UI framework in you starter?

**Comment by EmaSuriano** [comment]
Hey, what do you mean by `use`? This is a React project, you can install the dependencies you want and render them without any problem. The only thing to consider is sometimes you might need to add some plugin to the Gatsby config. [Here](https://www.gatsbyjs.org/starters/jaxx2104/gatsby-starter-bootstrap/) is a starter using `bootstrap`.

One last word, beware of this changes because you are going to move from the main branch and when I publish a new version or fix some bug, your merge is going to be total chaos.

Hope the answer is clear 😄

**Comment by EmaSuriano** [comment]
Any updates on this @azrijamil ?
