### ISSUE TITLE
Layout flash on page load

### ISSUE THREAD

**Issue by JacobJaffe** [EmaSuriano/gatsby-starter-mate#54]
First off, thanks for this awesome starter! It's been immensely useful for diving into Gatsby. 

An issue I'm running into: the Text Loop in the landing page has a layout issue on the page load. it immediately justifies left before centering, almost like it's repositioning after mounting. 

This only occurs for me on production builds (_not_ in development mode). It also only seems to occur in firefox for me. 

This occurs both for the cloned repo and for the live demo site. 

Any thoughts and/or help on this would be appreciated!

**Comment by EmaSuriano** [comment]
Hey, @JacobJaffe sorry for the delayed on answering. I took a look at the issue and the problem was related to `react-text-loop`, that has this weird behavior when it starts ... Anyways, I fixed it with applying a horizontal margin with `auto` and now it should be ok! 

Please let me know if you consider this issue closed, so we can close it 😄

**Comment by JacobJaffe** [comment]
Tried out the fix, it works! Thanks for the help on this.
