### ISSUE TITLE
Use local markdown files instead of Contentful

### ISSUE THREAD

**Issue by WieFel** [EmaSuriano/gatsby-starter-mate#750]
Hi @EmaSuriano.
Could you give me a quick hint on how it would be possible to use local markdown `.md` files to deliver the content for the web page, instead of using the Contentful CMS?

I already accomplished that previously using this gatsby starter in my repo [here](https://github.com/WieFel/my-portfolio-page). But now I want to update my page to the new version of this starter...

**Comment by EmaSuriano** [comment]
Hey @WieFel! I don't have any plans to make this starter work without the CMS, because it's one of the features of it. 

As an alternative, you can use the [Shadowing feature from Gatsby Themes](https://www.gatsbyjs.com/docs/how-to/plugins-and-themes/shadowing/) and then replace the hooks of data fetching from Contentful. They are located inside the `hooks` folder of the [gatsby-theme-mate](https://github.com/EmaSuriano/gatsby-theme-mate). The only thing to take care of is to keep the same data structure so then you don't have to modify the components as well :)

**Comment by WieFel** [comment]
@EmaSuriano is it possible to disable the initialisation/initial connection checking of the `gatsby-source-contentful`?
The problem is, when I try to run `gatsby develop`, I get an error because contentful cannot connect correctly...
<img width="1291" alt="image" src="https://user-images.githubusercontent.com/8345062/143783575-5854ffd3-2326-47bc-86d0-142be28970de.png">
However, I would simply wanna skip that step of connection...
