### ISSUE TITLE
No pages

### ISSUE THREAD

**Issue by SeaOfDreams** [EmaSuriano/gatsby-starter-mate#897]
After having successfully run the build (locally and on Netlify), I wanted to edit the code on the Home Page to delete the "writing" section, but my src/gatsby-theme-mate folder contains just an .empty file (I see the same here on your repository), while I believe there should be both the / (main) page and the 404 page inside this folder. 
Any idea why?

**Comment by EmaSuriano** [comment]
Hi,

The reason for the empty `src` was because this project was using the Gatsby Theme feature, where most of the code of the starter was extracted into an external dependency that can be extended through changes in the files inside the `src` folder.

I decided to deprecate the theme, and now you can freely clone the project and have access to the code of the project, where you can even change the structure of the code if you are not happy with it. 

For more information about the change, you can refer to the merged PR --> #924
